# environments/dev/values-postgres.yaml
sealedAppSecret:
  name: "app-secret"
  encryptedDatabaseUrl: "AgBCDVRunlLpC+FbJAbAP5GQDGjhOWSUlqvpxFxSY4XrX7ZcCyWYFptRbJeqTh7cKb3vRmQuAEuIfs4d3ROBpSarZFXzD5UhaXlVHC5igTT1mNyQIG1umfJif9xvZrCnivwYZo+QlfhFO5sbp9y2WA4AIFrrSZDzcU/9DkpA4GDD7h7OvWSCTai3wswAFmvq7sc3h/37MAd9PrRQvCiM9Wa34B6fssakl5rRyS0CPEmmD+5VN1ffQ8OT1Ou32UYBhkGvXJyR0p2gfx/uw4ukDJopZOW+5s2SQdHksBml7iSeS1zDQKMXQJqFNl9VQ9CDFnbzcX865ErgT3CtYJFDLjXvWaqPwYu7UD3mpuXf2FC4jmu1M/BkepDTqPbO3OqS99D2ISwR9TuX5ZIYjEz3xsh0ejXudabiur+0/8Yd1oQ9nCTd4Xqd5F/kObLigdiCIa0wEeoPOwWUae1DlXVTULduTuWcM/QFSHq3htKgolsotBhSAQ6LITmihSYL5IX6xhx+47tSUotHIwmbYyMBXisnN9YbLxQlD/oHxyv089FvuMn7lBkXBEJvgA8k4dnUp82/mV/hZyF1Eqfs1XUOMssv5QiZkJXPXVl0E7fhyxSkaHE+0NzDoKli2eWbWdfCIuqffI86egCnbx1J3bUAVLoec/1vZ/fz7iQCkuSwDkZDnw4Z2hMFI3Q82eHmtBm4ASNmiIYLXzD81KmRI1e0sDo2EK4Zeh5f9Xe0vbBhnxL9QC60IBzS9tj7qa8w2TsAw+Sup5u0eKTk1Z1RjVPGnYxMelEA7HPxA4E+"
sealedAdminSecret:
  name: "admin-secret"
  encryptedDatabaseUrl: "AgBev7hRxTqwyn2j09F6WpU6ofe4CiNeoixGo+f1MpZH1feqkqRWlDBdPO/mWUGKqH7Dailkpu8zZrTcFQVqOlTLT2I0UZWN7oLkTCPuzSJY1GnP1cWwyGXWfFyYa2EsJdLGKtufgDZKUD2wM4lN/uMtrsvlIDAix5c1QU8dgTM1GCd/1tdkQxlJAOYbhHYseZ7CTL1D2ez5oJDeD5sAC06grracPCh2C/+PA5lPY9Qe5NIC5CTIX9STt1G+JhFheLyYABtaaZ8Ab7EtLEwXaBTVdC1eovtFzkm2IiXJdTW4PUjmztaj3eJXRzff24UWZ0tzTP5e3e4umEWXtmC/VGGTaKVSpR0HYq+eir51AsmV3J+tZdo4VekCr+89wJ0p0vMEMwuKjEX5G8ryJDSbr2H7uk5BHen43Q40Bj8oypIHZRYfXsmVVcW/tpDS1VzRyCX+nLlFPVVhpE0PjkuBxxizxYnBje1XuZaLTR+8e3ESR2MDVvjjde1GYuGgSA+OS6xcVTvL+7fbPrQsX+O6gZZne5Wit2anI+o2SbOEKia9cTFLWFvDNbrdDRAOtj1KcsopMU8zFhHXVTDcaAQ6uo0WflwaAC+2W/1vthvsoXdTCcMjkNFTNX529VvbfuxfueX7c46/cXnHUnflu9priZrjSBPUcf0w+QW1uKbshdbm0OexdyDsozd7GofazQ27OWdCaB362daF+wecAO4Xxe4INcp4Moy5DBlJgIFMJ1XKqJyy0JTZr7M2Nrl2U2n3mH2ccWu+FDsCLe6+4bDP5Rrp5g5Lo8n5E3oOoyyM"

postgresql:
  fullnameOverride: postgres

  auth:
    username: app-user
    database: webhook_task_pipeline
    existingSecret: postgres-secret
    # secretKeys:
    #   adminPasswordKey: postgres-password
    #   userPasswordKey: password
    # Those are already the canonical Bitnami names. Check values.yaml line: 188

  primary:
    persistence:
      enabled: true
      size: 1Gi

    resources:
      requests:
        memory: 128Mi
        cpu: 100m
      limits:
        cpu: 250m
        memory: 256Mi

  readReplicas:
    replicaCount: 0

# DEFAULTS:
  # backup.enabled: false (default)
  # tls.enabled: false (default)
  # ldap.enabled: false (default)
  # ServiceAccount and RBAC kept default
  # metrics.enabled: false (default) -- but we'll eventually want to enable this for monitoring and alerting
