# platform/kube-prom-stack/values.yaml
prometheus:
  prometheusSpec:
    retention: 7d
    resources:
      requests:
        cpu: "150m"
        memory: "512Mi"
      limits:
        cpu: "500m"
        memory: "1Gi"
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: standard
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi
    replicas: 1

alertmanager:
  alertmanagerSpec:
    replicas: 1
    resources:
      requests:
        cpu: "50m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "256Mi"
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: standard
          resources:
            requests:
              storage: 1Gi

grafana:
  replicas: 1
  persistence:
    enabled: true
    storageClassName: standard
    size: 2Gi
  admin:
    existingSecret: grafana-admin-credentials
    userKey: admin-user
    passwordKey: admin-password
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"
  
  grafana.ini:
    server:
      root_url: "https://grafana.dev.local"
  
  route:
    main:
      enabled: true
      apiVersion: gateway.networking.k8s.io/v1
      kind: HTTPRoute
      parentRefs:
        - name: platform-gateway
          namespace: platform-gateway
      hostnames:
        - grafana.dev.local
      
      matches:
        - path:
            type: PathPrefix
            value: /

prometheus-node-exporter:
  resources:
    requests:
      cpu: "25m"
      memory: "32Mi"
    limits:
      cpu: "100m"
      memory: "64Mi"