apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-root-ca
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  isCA: true

  commonName: local-root-ca

  secretName: local-root-ca-secret

  duration: 87600h # 10 years

  issuerRef:
    name: bootstrap-selfsigned
    kind: ClusterIssuer
  privateKey:
    algorithm: RSA
    size: 4096