apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-pki
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  project: platform
  source:
    repoURL: https://github.com/samimassoud/webhook-task-pipeline-dl.git
    targetRevision: main
    path: platform/argo-phase/platform/pki
  destination:
    server: https://kubernetes.default.svc
    namespace: pki
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
