apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-postgres
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"

spec:
  project: platform

  source:
    repoURL: https://github.com/samimassoud/webhook-task-pipeline-dl.git
    targetRevision: main
    path: platform/argo-phase/charts/platform-postgres

    helm:
      valueFiles:
        - ../../environments/dev/values-platform-postgres.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: webhook-task-pipeline

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true