apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"

spec:
  project: platform

  source:
    repoURL: https://github.com/samimassoud/webhook-task-pipeline-dl.git
    targetRevision: main
    path: platform/argo-phase/charts/platform-gateway

    helm:
      valueFiles:
        - ../../environments/dev/values-envoy-gateway.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: platform-gateway
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true