apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: webhook-task-pipeline
spec:
  clusterIP: None
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432