---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.sealedAppSecret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "webhook-task-pipeline.labels" . | nindent 4}}
spec:
  encryptedData:
    DATABASE_URL: {{ .Values.sealedAppSecret.encryptedDatabaseUrl }}
  template:
    metadata:
      name: {{ .Values.sealedAppSecret.name }}
      namespace: {{ .Release.Namespace }}
    type: Opaque
