---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.sealedAdminSecret.name }}
  namespace: {{ .Release.Namespace}}
  labels:
    {{- include "webhook-task-pipeline.labels" . | nindent 4}}
spec:
  encryptedData:
    DATABASE_URL: {{ .Values.sealedAdminSecret.encryptedDatabaseUrl}}
  template:
    metadata:
      name: {{ .Values.sealedAdminSecret.name }}
      namespace: {{ .Release.Namespace}}
    type: Opaque
