---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.sealedAppSecret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    DATABASE_URL: {{ .Values.sealedAppSecret.encryptedDatabaseUrl }}
  template:
    metadata:
      name: {{ .Values.sealedAppSecret.name }}
      namespace: {{ .Release.Namespace }}
    type: Opaque
