---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.sealedAdminSecret.name }}
  namespace: {{ .Release.Namespace}}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  encryptedData:
    DATABASE_URL: {{ .Values.sealedAdminSecret.encryptedDatabaseUrl}}
  template:
    metadata:
      name: {{ .Values.sealedAdminSecret.name }}
      namespace: {{ .Release.Namespace}}
    type: Opaque
