nameOverride: ""
fullnameOverride: "app"

image:
  repository: ""
  tag: ""
  pullPolicy: ""

sealedAppSecret:
  encryptedDatabaseUrl: ""
  name: ""

api:
  replicaCount: 1 
  port: 3000
  service:
    port: 80
    targetPort: 3000

  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    cpuUtilization: 80
  
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "500m"

postgres:
  service:
    name: postgres
    port: 5432
  database: webhook_task_pipeline
  readinessCheck:
    image:
      repository: postgres
      tag: "16-alpine"
    intervalSeconds: 2

gateway:
  parentRef:
    name: ""
    namespace: ""